import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/AppNavbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Idea vault",
  description: "Generated by S.B. Himel",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
      suppressHydrationWarning 
    >
      <body className="min-h-full flex flex-col bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-50 transition-colors duration-300">
        <ThemeProvider>
          <AppNavbar />
          
         
          <main className="flex-grow">
            {children}
          </main>
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
